version: '3.8'
services:
  rag_agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    volumes:
      - ./data:/app/data