name: Backend CI

on:
    push:
        branches: [ main ]
        paths:
          - 'backend/**'
    pull_request:
        branches: [ main ]
        paths:
          - 'backend/**'
jobs:
    build:
        runs-on: ubuntu-latest

        env:
          HUGGINGFACE_API_KEY: 
          ENV: test

        steps:
        - uses: actions/checkout@v4

        - name: ENV
          run: |
            echo "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}" >> $GITHUB_ENV
            echo "ENV=test"  >> $GITHUB_ENV
            echo "$HUGGINGFACE_API_KEY"
            echo "$ENV"

        - name: Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'
        
        - name: Install Dependencies
          run: |
            cd backend
            python -m pip install --upgrade pip
            sed -i 's/faiss-gpu/faiss-cpu/' requirements.txt
            pip install -r requirements.txt

        - name: Test
          env:
            HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
            ENV: test
          run: |
            cd backend
            pytest