name: Backend CI

on:
    push:
        branches: [ main ]
        paths:
          - 'backend/**'
    pull_request:
        branches: [ main ]
        paths:
          - 'backend/**'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'
        
        - name: Install dependencies
          run: |
            cd backend
            python -m pip install --upgrade pip
            sed -i 's/faiss-gpu/faiss-cpu/' requirements.txt
            pip install -r requirements.txt
        
        - name: Run tests
          run: |
            cd backend
            pytest

        - name: Lint with flake8
          run: |
            cd backend
            pip install flake8
            flake8 .