name: Backend Python CI

on:
    push:
        branches: [ main ]
        paths:
          - 'backend/**'
    pull_request:
        branches: [ main ]
        paths:
          - 'backend/**'
jobs:
    build:
        environment: development
        runs-on: ubuntu-latest

        env:
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
          ENV: test

        steps:
        - uses: actions/checkout@v4

        - name: Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'
        
        - name: Install Dependencies
          run: |
            cd backend
            python -m pip install --upgrade pip
            sed -i 's/faiss-gpu/faiss-cpu/' requirements.txt
            pip install -r requirements.txt
        
        - name: Test
          run: |
            cd backend
            pytest -s

        - name: Run flake8
          run: |
            cd backend
            flake8 .

        - name: Run black
          run: |
            cd backend
            black --check .