name: Docker Image CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - name: Build and push Backend Docker image
              run: |
                IMAGE_TAG=testmancer/backend:$(date +%s)
                docker build . --file Dockerfile.backend --tag $IMAGE_TAG
                docker push $IMAGE_TAG
                
            - name: Build and push Frontend Docker image
              run: |
                IMAGE_TAG=testmancer/frontend:$(date +%s)
                docker build . --file Dockerfile.frontend --tag $IMAGE_TAG
                docker push $IMAGE_TAG
