name: Frontend Python CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  placeholder:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install Dependencies
      run: |
        cd frontend
        python -m pip install --upgrade pip
        sed -i 's/faiss-gpu/faiss-cpu/' ../requirements.txt
        pip install -r ../requirements.txt
    
    - name: Test
      run: |
        cd frontend
        pytest -s

    - name: Run flake8
      run: |
        cd frontend
        flake8 .

    - name: Run black
      run: |
        cd frontend
        black --check .
