name: Frontend CI (Placeholder)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  placeholder:
    runs-on: ubuntu-latest
    
    steps:
    - name: Placeholder step
      run: echo "Frontend CI placeholder - No tests running at this time"